language: python
python:
- '3.5'
- '3.5-dev'
- 'nightly'
install:
- pip install pypandoc
- make init
- pip install coveralls
script: make test
notifications:
  email: false
after_success: coveralls
addons:
  apt:
    packages:
      - pandoc
